project_id = "nvbqurstnjryhtmqhucv"

[functions.analyze-evidences]
verify_jwt = false

[functions.analyze-disc]
verify_jwt = false

[functions.infer-disc-profile]
verify_jwt = false

[functions.generate-strategic-plan]
verify_jwt = false

[functions.analyze-role-fit]
verify_jwt = false

[functions.extract-project-context]
verify_jwt = false
